name: CMake on multiple platforms

env:
  WORKSPACE: ${{ github.workspace }}/all
  BUILD_OUTPUT_DIR: ${{ github.workspace }}/all/build
  BUILD_TYPE: Release

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.cmake'
      - '**/CMakeLists.txt'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.cmake'
      - '**/CMakeLists.txt'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        c_compiler: [ gcc, clang, cl ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: clang
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: >
          cmake -B ${{ env.BUILD_OUTPUT_DIR }} -S ${{ env.WORKSPACE }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - name: Build
        run: cmake --build ${{ env.BUILD_OUTPUT_DIR }} --config ${{ env.BUILD_TYPE }}
      - name: Test
        run: |
          cd ${{ env.BUILD_OUTPUT_DIR }}
          ctest --build-config ${{ env.BUILD_TYPE }}
